[[about-doc]]
= About the Documentation
:linkattrs:
This section provides a brief overview of Reactor reference documentation. You do not
need to read this guide in a linear fashion. Each piece stands on its own, though they
often refer to other pieces.

== Latest Version & Copyright Notice
The Reactor reference guide is available as HTML documents. The latest copy is available
at https://projectreactor.io/docs/core/release/reference/index.html

Copies of this document may be made for your own use and for distribution to others,
provided that you do not charge any fee for such copies and further provided that each
copy contains this Copyright Notice, whether distributed in print or electronically.

== Contributing to the Documentation
The reference guide is written in
https://asciidoctor.org/docs/asciidoc-writers-guide/[Asciidoc], and you can find its sources at
https://github.com/reactor/reactor-core/tree/master/docs/asciidoc.

If you have an improvement or a suggestion, we will be happy to get a pull request from you!

We recommend that you check out a local copy of the repository so that you can
generate the documentation by running the `asciidoctor` gradle task and checking the
rendering. Some of the sections rely on included files, so GitHub rendering is
not always complete.

ifeval::["{backend}" == "html5"]
TIP: To facilitate documentation edits, most sections have a link at the end that opens
an edit UI directly on GitHub for the main source file for that section. These links are
only present in the HTML5 version of this reference guide. They look like the following:
link:https://github.com/reactor/reactor-core/edit/master/docs/asciidoc/aboutDoc.adoc[Suggest Edit^, role="fa fa-edit"] to <<about-doc>>.
endif::[]

== Getting Help
You can reach out for help in several ways with Reactor:

* Get in touch with the community on https://gitter.im/reactor/reactor[Gitter].
* Ask a question on stackoverflow.com at
https://stackoverflow.com/tags/project-reactor[`project-reactor`].
* Report bugs in Github issues. We closely monitor the following repositories:
https://github.com/reactor/reactor-core/issues[reactor-core] (which covers the
essential features) and https://github.com/reactor/reactor-addons/issues[reactor-addons]
(which covers reactor-test and adapters issues).

NOTE: All of Reactor is open source,
https://github.com/reactor/reactor-core/tree/master/docs/asciidoc[including this
documentation]. If you find problems with the docs or if you want to improve them,
please https://github.com/reactor/.github/blob/master/CONTRIBUTING.md[get involved].

== Where to Go from Here
* 如果你喜欢直接开始代码，请跳转到  <<getting-started>>
* 如果你第一次接触 reactive 编程, 你应该从
<<intro-reactive>> 开始.
* 如果你比较熟悉 Reactor 相关感念，只是想为工作中找些正确到方法，但是对用哪些运算符有不是很了解，你可以访问 <<which-operator>> 附录.
* 为了更深入对了解 Reactor 核心功能, 点击 <<core-features>> 学习相关内容:
** 更多对学习了解 Reactor's 反应类型，在 <<flux>> 和 <<mono>>
章节中.
** 如何选中线程上下文去使用 <<schedulers,a scheduler>>.
** 如何捕获处理错误 <<error.handling>> 章节.
* Unit 单元测试? 是以通过 `reactor-test` 项目做到! 查看 <<testing>>.
* <<producing>> 学习跟多高级的方法去创建 reactive 源码.
* 其他高级主题都在 <<advanced>>.
